version: '2'

services:

### Workspace Utilities Container ###########################

    workspace:
        build: ./workspace
        volumes_from:
            - volumes_source
        tty: true

### Apache Server Container ##################################

    apache2:
        build: ./apache2

        volumes_from:
            - volumes_source
        volumes:
            - ./logs/apache2:/var/log/apache2
        ports:
            - "80:80"
        links:
            - workspace
            - mysql

### MySQL Container #########################################

    mysql:
        build: ./mysql
        ports:
            - "3306:3306"

### PHP Application Code Container ######################

    volumes_source:
        build: ./volumes/application
        volumes:
            - ../my-php-app:/var/www
